### ISSUE TITLE
onComplete event does not work when different tab is active

### ISSUE THREAD

**Issue by caike** [caike/jQuery-Simple-Timer#10]
When using multiple tabs in Safari or Chrome, the `onComplete` event is not properly fired if a different tab is active when the timer finishes.

**Comment by iaroel** [comment]
Same here.
Any solution on this?

**Comment by caike** [comment]
I've done some quick research and still have not found a simple solution. This is not a priority for me atm so I'll come back to this in a few. In the mean time, I'm open to suggestions and PRs.

**Comment by caike** [comment]
My understanding is that JS is suspended on inactive tabs. There are no simple solutions that work across all browsers. However, I believe this fix b6d74a8fd9f3dc05a13405348b11550a4eab57d4 can mitigate the problem.
