### ISSUE TITLE
how can i stop the timer

### ISSUE THREAD

**Issue by GioDgo** [caike/jQuery-Simple-Timer#12]
hi,excuse me , im working with  your timer but i dont know how can i stop the timer ? please
thanks
sincerely

**Comment by caike** [comment]
There's no such feature on `master

**Comment by hdenguir** [comment]
This code it's working fine for me to stop timer : 
`$('.timer').trigger('complete');`

**Comment by caike** [comment]
@hdenguir that's definitely one way to do it
