### ISSUE TITLE
missed onComplete event when computer is asleep

### ISSUE THREAD

**Issue by mtheimer** [caike/jQuery-Simple-Timer#16]
Using Simple-Timer as an auto-logout for a private database I encountered an issue: e.g. the timer is set to 30', the computer goes to standby at 28' and is re-activated 4 minutes later, the timer is at 23h 58', having missed the onComplete event at 0'00''.
Inserting a new line 125
`if (timeLeft < 0) timeLeft = 0;`
did solve this for me.

**Comment by caike** [comment]
Thanks for catching that and for the code suggestion! I will add this to the code base soon.
