### ISSUE TITLE
Unable to re-set timer to different duration.

### ISSUE THREAD

**Issue by lowyoujian** [caike/jQuery-Simple-Timer#20]
Hi, i tried using the timer with data-seconds-left =2 , after the 2 seconds run out, i run some ajax, after ajax returns, i want to run the timer with a 10 seconds duration. 
Any idea on how to make this possible? 
The timer seems to run back the 2 seconds timer even after i change the data-seconds-left to 10 seconds via $('#timer').attr('data-seconds-left',10);
Thanks.

**Comment by caike** [comment]
With the current API, here's a hack that will get you there:

```
let timerElement = $('.timer'); 
timerElement.startTimer({
  onComplete: function(){
  yourAjaxFunction(url, function(){
      timerElement.data('seconds-left', 10); // add new duration
      timerElement.trigger('resume'); // hack!!!
  }, 3000);
}
```

I call it a hack because the 'resume' event is currently a private API and shouldn't be relied upon. I have a couple ideas I'll work on later this week but for now this hack should do.

**Comment by lowyoujian** [comment]
oh it worked even with 
timerElement.startTimer() instead of timerElement.trigger('resume');

$('#timer').attr('data-seconds-left',10) seems to be no working in this case. Just had to use the .data('seconds-left',10).

Thanks.

**Comment by caike** [comment]
Good to know! Appreciate you letting me know 👍  I'll add this to the docs for future reference.
