### ISSUE TITLE
Jquery Timer is not working in IE browser

### ISSUE THREAD

**Issue by drathi** [caike/jQuery-Simple-Timer#28]
Hi Carlos,

I am using this code . It is not working in any version of IE. Although it works fine in all other browsers like Mozilla,Chrome and Safari. Could you provide any solution.

Thanks,
Deepak

**Comment by caike** [comment]
Could you provide more details about the error you are running into ? Unfortunately I don't have IE so I can't try and reproduce it myself.

**Comment by caike** [comment]
Had someone else test this on latest IE and it works fine. Closing this but I'm still interested in hearing more details about your error. Please feel free to re-open.
