### ISSUE TITLE
timer pause and play 

### ISSUE THREAD

**Issue by sayan0020** [caike/jQuery-Simple-Timer#29]
how to pause the timer by clicking on some button without clicking on the timer ? I've tried all the suggestion you gave and from the previous issues solved. But it didn't help me out. Please response ASAP.

**Comment by tamaghna91** [comment]
Hope what your are asking I can help you in some sort like this

` var time_event_flag = 0;
 function start_timer() {
      if(!time_event_flag) {
          $("#mock-time-left").startTimer({
              allowPause: true
        });
    } else {
          $("#mock-time-left").trigger("click");
    }
}
function stop_timer() {
      $("#mock-time-left").trigger("click");
      time_event_flag = true;
}
`

**Comment by caike** [comment]
Assuming you have button like 

```HTML
<button id="button-pause">Pause/Resume</button>
```
 You could do something like this

```javascript
const timer = $('.timer-pause');
timer.startTimer({
  allowPause: true
});

$("#button-pause").on("click", () => timer.trigger("click"));
```

And that should work!
