### ISSUE TITLE
Ho to debugg this?

### ISSUE THREAD

**Issue by kaspar-allenbach** [caike/jQuery-Simple-Timer#33]
I used your plugin severyl times but no it's not working anymore.

I load it like this:

```
<div class="sunLocDuration timer itIsDay" data-seconds-left="19999"></div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.rawgit.com/caike/jQuery-Simple-Timer/1bc86823/jquery.simple.timer.js"></script>
<script>
  $( document ).ready(function() {
    $('.timer').startTimer();
  });
</script>
```

This does nothing. It doesnt even throw an error. It simply doesn't work. What's the catch here?

**Comment by caike** [comment]
Sorry for the delay. Have you figured this out ? 
I'm running your code and it seems to be working fine in the latest Firefox, Chrome and Safari.
Closing this for now but let me know if you need further help.
