### ISSUE TITLE
StopTimer and clearInterval

### ISSUE THREAD

**Issue by manutepowa** [caike/jQuery-Simple-Timer#34]
Hi!!
I have a timer and i want a function to stop timer.
```js
var inter = $(`#my-record-${id} .timer`).startTimer();
```
But the library don't have any function to stop.

Thanks

**Comment by caike** [comment]
The following should work:

```javascript
var inter = $(`#my-record-${id} .timer`).startTimer({ allowPause: true });

// This function will pause and also resume
function toggleTimer(){
  $(`#my-record-${id} .timer`).trigger('click');
}
```

Let me know how this goes and feel free to re-open this issue if you run into any issues.
Thank!
