### ISSUE TITLE
bug (or not) with pause and onComplete

### ISSUE THREAD

**Issue by titrax35** [caike/jQuery-Simple-Timer#37]
When I use the function : 
 $(function(){
    $('.timer').startTimer({
      onComplete: function(){
        console.log('Complete');
      },
      allowPause: true
    });
If you do nothing, the console show 'Complete', but if you pause it (by clicking on timer), at the end time, there is nothing on the console to try : 
https://rawgit.com/caike/jQuery-Simple-Timer/master/examples/index.html

**Comment by caike** [comment]
Thank you for catching this! It's been fixed.
