### ISSUE TITLE
Set data-seconds-left value using jquery on page load

### ISSUE THREAD

**Issue by OsamaMunawar** [caike/jQuery-Simple-Timer#41]
Thanks for this plugin its really helpful. Can you please tell me how can I set the value using jquery of this below tag. I cannot give time to data-seconds-left with my h4 tag. Its remaining time is coming from the server-side. So, I need to assign it on page load. 

<h4 class='timer'></h4>

**Comment by caike** [comment]
I'm not exactly sure how you are rendering your timer element, but if you are rendering the entire page on the server side, you can use string interpolation on your server side language. Something like:

`<h4 class='timer' data-seconds-left=${seconds}></h4>` which will be rendered on the server and then sent back to the client.

Or if you are making a JS call to the server after the element is already rendered, then you can do something like:

```
$.get("/remaining-time", function( seconds ) {
  $("h2").data("data-seconds-left", seconds);
  $("h2").startTimer();
});
```

Hope this works! Feel free to re-open if you need more help.

**Comment by OsamaMunawar** [comment]
Thanks, it worked for me. Thank you sir
